name: xplora
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:

  uses-material-design: true

  assets:
  - assets/svg/

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jura-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jura-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jura-Light.ttf
          weight: 300
        - asset: assets/fonts/Jura-SemiBold.ttf
          weight: 600
  