name: xplora
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.23+23

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.16
  google_fonts: ^6.3.2
  percent_indicator: ^4.2.3
  qr_code_scanner: ^1.0.1
  mobile_scanner: ^7.1.4
  firebase_auth: ^5.1.2
  url_launcher: ^6.3.1
  map_launcher: ^4.4.3
  location: ^7.0.0
  geolocator: ^10.0.0
  carousel_slider: ^5.0.0
  app_links: ^6.3.2
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.1.0
  cached_network_image: ^3.4.1
  lucide_icons: ^0.257.0
  image_picker: ^1.0.7
  google_maps_flutter: ^2.14.0
  geocoding: ^3.0.0
  google_places_flutter: ^2.0.9
  path: ^1.9.0
  shimmer: ^3.0.0
  share_plus: ^10.1.2
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.7
  device_preview_plus: ^2.3.2
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  path_provider: ^2.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/data/
    - assets/category_icons/

  fonts:
    - family: Jura
      fonts:
        - asset: assets/fonts/Jura-Regular.ttf
          weight: 400
        - asset: assets/fonts/Jura-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jura-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jura-Light.ttf
          weight: 300
        - asset: assets/fonts/Jura-SemiBold.ttf
          weight: 600

    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png/xplora-xp-logo-solid.png" # Your icon image path
  adaptive_icon_background: "#F0EFEB" # Background for Android adaptive icon
  remove_alpha_ios: true # Remove alpha from iOS icons
  background_color_ios: "#F0EFEB" # Background color for iOS icons

flutter_native_splash:
  color: "#ffffff" # Background color of splash screen
  image: assets/png/xplora-logo-solid.png # Your splash image
  android: true
  ios: true
  fullscreen: true # Optional, hides the status bar on splash screen
