// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE77UbQfYXo-3V9CuEyvfRDHUZ4Rg_sTE',
    appId: '1:441929013315:web:a888cfe4e820b2d9a21cf6',
    messagingSenderId: '441929013315',
    projectId: 'xplra-1',
    authDomain: 'xplra-1.firebaseapp.com',
    storageBucket: 'xplra-1.appspot.com',
    measurementId: 'G-PQF6QF6L7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSLbMKMPZfns0MkLMveGBkVHD5wZ8npEw',
    appId: '1:441929013315:android:d4dad027258cbb2fa21cf6',
    messagingSenderId: '441929013315',
    projectId: 'xplra-1',
    storageBucket: 'xplra-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0gazYL_5ODAextQ9eKUo_iLBUWgTDeyA',
    appId: '1:441929013315:ios:78903518c7986f87a21cf6',
    messagingSenderId: '441929013315',
    projectId: 'xplra-1',
    storageBucket: 'xplra-1.appspot.com',
    iosBundleId: 'com.example.xplora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0gazYL_5ODAextQ9eKUo_iLBUWgTDeyA',
    appId: '1:441929013315:ios:78903518c7986f87a21cf6',
    messagingSenderId: '441929013315',
    projectId: 'xplra-1',
    storageBucket: 'xplra-1.appspot.com',
    iosBundleId: 'com.example.xplora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE77UbQfYXo-3V9CuEyvfRDHUZ4Rg_sTE',
    appId: '1:441929013315:web:95051167c23a5796a21cf6',
    messagingSenderId: '441929013315',
    projectId: 'xplra-1',
    authDomain: 'xplra-1.firebaseapp.com',
    storageBucket: 'xplra-1.appspot.com',
    measurementId: 'G-Z7WLPJ2WRN',
  );
}
